import { NavbarContextProvider } from '@/contexts/NavbarContext';

import Footer from '@/components/layout/footer/Footer';
import Header from '@/components/layout/header/Header';
import Navbar from '@/components/layout/navbar/Navbar';

import { noto, yoonGothic } from '@/styles/font';
import '@/styles/globals.css';

import { SWRProvider } from './swr-provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body
        className={`
            flex flex-col ${yoonGothic.variable} ${noto.variable} text-neutral-700 font-normal
            sm:flex-row
        `}
      >
        <NavbarContextProvider>
          <Navbar />
          <div className="overflow-auto flex-1">
            <div className="min-w-fit min-h-screen flex flex-col flex-1">
              <Header />
              <main className="flex-1">
                <SWRProvider>
                  <div className="flex-1">{children}</div>
                </SWRProvider>
              </main>
              <Footer />
            </div>
          </div>
        </NavbarContextProvider>
      </body>
    </html>
  );
}
