import { NavbarContextProvider } from '@/contexts/NavbarContext';

import Footer from '@/components/layout/footer/Footer';
import Header from '@/components/layout/header/Header';
import Navbar from '@/components/layout/navbar/Navbar';

import { noto, yoonGothic } from '@/styles/font';
import '@/styles/globals.css';

import { SWRProvider } from './swr-provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body
        className={`grid grid-rows-[auto_1fr] grid-cols-[auto_1fr] ${yoonGothic.variable} ${noto.variable} text-neutral-700 font-normal`}
      >
        <NavbarContextProvider>
          <Navbar />
          <div className="overflow-auto">
            <Header />
            <main className="min-w-fit">
              <SWRProvider>{children}</SWRProvider>
            </main>
            <Footer />
          </div>
        </NavbarContextProvider>
      </body>
    </html>
  );
}
