import RootLayout from '../[locale]/layout';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <RootLayout params={{ locale: 'ko' }}>{children}</RootLayout>;
}
